### ISSUE TITLE
Regression test

### ISSUE THREAD

**Issue by ddugovic** [ddugovic/python-chess-annotator#8]
https://github.com/ddugovic/python-chess-annotator/actions does not cover everything.  In copying engine/UCI code from python-chess examples it is possible a regression may have been introduced.

**Comment by ddugovic** [comment]
I can't figure out how to run this code without installing from pypi, but now isn't a good time to publish either!

```
$ python annotator -f caruana-kasparov.pgn

An unhandled exception occurred: <class 'TypeError'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "annotator/__main__.py", line 767, in <module>
    main()
  File "annotator/__main__.py", line 757, in main
    raise e
  File "annotator/__main__.py", line 749, in main
    analyzed_game = analyze_game(game, args.gametime,
  File "annotator/__main__.py", line 589, in analyze_game
    game, root_node, ply_count = classify_opening(game)
  File "annotator/__main__.py", line 480, in classify_opening
    classification = classify_fen(fen, ecofile)
  File "annotator/__main__.py", line 333, in classify_fen
    with open(ecopath, 'r') as ecofile:
TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper
sys:1: RuntimeWarning: coroutine 'popen_uci' was never awaited

```

**Comment by ddugovic** [comment]
Progress:

```
python annotator -f caruana-kasparov.pgn

An unhandled exception occurred: <class 'AttributeError'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "annotator/__main__.py", line 768, in <module>
    main()
  File "annotator/__main__.py", line 758, in main
    raise e
  File "annotator/__main__.py", line 750, in main
    analyzed_game = analyze_game(game, args.gametime,
  File "annotator/__main__.py", line 628, in analyze_game
    judgment = judge_move(prev_node.board(), node.move, engine,
  File "annotator/__main__.py", line 201, in judge_move
    analysis = engine.play(board, limit, game=object())
AttributeError: 'coroutine' object has no attribute 'play'
sys:1: RuntimeWarning: coroutine 'popen_uci' was never awaited
```

**Comment by PedanticHacker** [comment]
@ddugovic, `asyncio.run()` only runs the `main()` coroutine, but the coroutine `judge_move()` is not run, hence `engine.play()` is not awaited. Hope that helps.

**Comment by ddugovic** [comment]
Thanks however after my last comment I added more code, which still fails testing.  I'm tempted to archive this project since I can't support it and I doubt anyone uses it:

```
python annotator -f caruana-kasparov.pgn
<PlayResult at 0x7fb8ff5a52e0 (move=f5f3, ponder=e2f3, info={}, draw_offered=False, resigned=False)>

An unhandled exception occurred: <class 'KeyError'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "annotator/__main__.py", line 768, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "annotator/__main__.py", line 757, in main
    raise e
  File "annotator/__main__.py", line 749, in main
    analyzed_game = await analyze_game(game, args.gametime,
  File "annotator/__main__.py", line 627, in analyze_game
    judgment = await judge_move(prev_node.board(), node.move, engine,
  File "annotator/__main__.py", line 202, in judge_move
    judgment["bestmove"] = analysis.info["pv"][1][0]
KeyError: 'pv'
```

I have local changes which I have no recollection of making:

```
diff --git a/annotator/__main__.py b/annotator/__main__.py
index 8068b1e..2cda7d3 100755
--- a/annotator/__main__.py
+++ b/annotator/__main__.py
@@ -198,6 +198,7 @@ async def judge_move(board, played_move, engine, searchtime_s):
     limit = chess.engine.Limit(time=searchtime_s / float(2.0))
     analysis = await engine.play(board, limit)

+    print(analysis)
     judgment["bestmove"] = analysis.info["pv"][1][0]
     judgment["besteval"] = eval_numeric(analysis)
     judgment["pv"] = analysis.info["pv"][1]
@@ -763,6 +764,7 @@ async def main():


 if __name__ == "__main__":
+    asyncio.set_event_loop_policy(chess.engine.EventLoopPolicy())
     asyncio.run(main())
```
